version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=guest
      - POSTGRES_PASSWORD=welcome1
      - PGDATA="/data/postgres"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - postgres:/mnt/data/.postgres
      # - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  #pgadmin:
  #  container_name: pgadmin4_container
  #  image: dpage/pgadmin4:latest
  #  restart: always
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #    PGADMIN_DEFAULT_PASSWORD: welcome1
  #  ports:
  #    - "5050:80"
volumes:
  postgres:
